### ISSUE TITLE
demo/import.R wrote demo.RData result into wrong directory

### ISSUE THREAD

**Issue by pshannon-bioc** [Bioconductor/MotifDb#2]
Tanja reports (accurately!):

<code>
I trial ran the code you posted online but cannot find the demo.RData file that was saved. It should be saved to the same folder, shouldn't it?
</code>

So I revised run(dataDir) function to read like this:
![screen shot 2014-02-04 at 1 04 07 pm](https://f.cloud.github.com/assets/2285629/2081196/f46e9848-8ddf-11e3-9709-00dc10392039.png)

**Comment by b-long** [comment]
@pshannon-bioc

Paul, do we know if this issue has been addressed and whether it can be closed?

cc/ @vobencha @dtenenba

**Comment by pshannon-bioc** [comment]
Hi Brian,

I have lost context on this, I am sorry.  I do not recall what code I posted online.  Tanja appears to have solved her problem.  In the absence of that posted code, there is not much I can do.

Shall we close this?

**Comment by b-long** [comment]
Hi Paul,
Yes, that seems reasonable.  Any comment on #5 ?

Thanks, for getting back to us :+1: :smile: 
Brian
