### ISSUE TITLE
jaspar2014 run.tests(directory); what directory?

### ISSUE THREAD

**Issue by pshannon-bioc** [Bioconductor/MotifDb#5]
Hi Tristan,
Great work on jaspar2014.  As almost always happens :} things don't -quite- work off of the original developer's machine.  Is there a test directory (perhaps even "../" which I can pass to import.R's run.tests so that run.tests has what it needs?

Thanks!

 - Paul

**Comment by b-long** [comment]
@pshannon-bioc 

Paul, do we know if this issue has been addressed and whether it can be closed?

cc/ @vobencha @dtenenba

**Comment by pshannon-bioc** [comment]
I finished off this project.

**Comment by b-long** [comment]
Great, thanks Paul! :+1:
